#!/usr/bin/env python3
"""Reproducible TPD mass-action, linker-ensemble and synthetic-assay workflow.

Python >=3.10. Install: python -m pip install numpy scipy matplotlib rdkit
Run: python run_task2_tpd_ternary_cooperativity.py
All calculations use nM, hours, and angstroms internally. No network is needed.
All figures, reports, tables, structures and validation are generated by this file.
Synthetic research model; no clinical dose recommendation or experimental claim.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import logging
import math
import platform
import subprocess
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path

try:
    import numpy as np
    import scipy
    from scipy.integrate import solve_ivp
    from scipy.optimize import brentq, least_squares, minimize_scalar, root
    from scipy.special import expit, logsumexp
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.colors import LogNorm
    import rdkit
    from rdkit import Chem
    from rdkit.Chem import AllChem, rdMolDescriptors
except ImportError as exc:
    raise SystemExit("Missing dependency. Run: python -m pip install numpy scipy matplotlib rdkit\n" + str(exc)) from exc

LOG = logging.getLogger("task2")
ALPHAS = (0.01, 1.0, 10.0, 100.0)
COLORS = ("#778493", "#3476A8", "#008F83", "#C46A23")
COMMIT_MESSAGE = "feat(task2): targeted protein degradation engine, ternary complex cooperativity & hook effect modeling"
REFERENCES = """1. [Douglass et al. (2013), A Comprehensive Mathematical Model for Three-Body Binding Equilibria](https://doi.org/10.1021/ja311795d).
2. [A suite of mathematical solutions to describe ternary complex formation (2020)](https://pmc.ncbi.nlm.nih.gov/articles/PMC7650257/).
3. [Gadd et al. (2017), Structural basis of PROTAC cooperative recognition](https://doi.org/10.1038/nchembio.2329).
4. [Affinity and cooperativity modulate ternary complex formation (2023)](https://www.nature.com/articles/s41467-023-39904-5).
5. [RDKit ETKDG and embedding API](https://www.rdkit.org/docs/source/rdkit.Chem.rdDistGeom.html).
6. [RDKit MMFF conformer optimization API](https://www.rdkit.org/docs/source/rdkit.Chem.rdForceFieldHelpers.html).
"""


@dataclass(frozen=True)
class Config:
    e_total_nm: float = 100.0
    t_total_nm: float = 100.0
    kd_e_nm: float = 10.0
    kd_t_nm: float = 100.0
    vmax_nm_h: float = 12.0
    km_nm: float = 10.0
    hours: float = 24.0
    basal_turnover_h: float = 0.0
    points: int = 181
    heatmap_points: int = 41
    conformers: int = 100
    seed: int = 20260910
    compatible_low_a: float = 8.0
    compatible_high_a: float = 12.0

    def validate(self):
        for name in ("e_total_nm", "t_total_nm", "kd_e_nm", "kd_t_nm", "vmax_nm_h", "km_nm", "hours"):
            value = getattr(self, name)
            if not np.isfinite(value) or value <= 0:
                raise ValueError(f"{name} must be finite and positive")
        if not np.isfinite(self.basal_turnover_h) or self.basal_turnover_h < 0:
            raise ValueError("basal_turnover_h must be finite and nonnegative")
        if self.points < 81 or self.heatmap_points < 5 or self.conformers < 100:
            raise ValueError("Use at least 81 dose points, 5 heatmap points and 100 conformers")
        if not (0 <= self.seed < 2**31 - 1):
            raise ValueError("seed must be in [0, 2**31-1)")
        if not (0 < self.compatible_low_a < self.compatible_high_a):
            raise ValueError("Invalid illustrative compatibility window")


class Equilibrium:
    """Positive log-concentration 3D root solver with independent scalar backup.

    Species order: P, E, T, EP, PT, EPT. A successful optimizer status alone
    is never accepted: log mass balance and physical bounds must also pass.
    """
    def __init__(self):
        self.counts = {"hybr": 0, "lm": 0, "scalar_fallback": 0}
        self.max_relative_balance_error = 0.0

    @staticmethod
    def validate_inputs(p0, e0, t0, ke, kt, alpha):
        values = np.array([p0, e0, t0, ke, kt, alpha], float)
        if not np.all(np.isfinite(values)) or min(p0, e0, t0) < 0 or min(ke, kt, alpha) <= 0:
            raise ValueError("Totals must be nonnegative; Kd and alpha must be positive and finite")

    @staticmethod
    def fixed_free(p, e0, t0, ke, kt, alpha):
        """Stable quadratic solution at fixed free P; supports NumPy arrays."""
        p = np.maximum(np.asarray(p, float), np.finfo(float).tiny)
        q = (ke + p) * (kt + p) / (alpha * p)
        # Scale before squaring: zero-dose vector lanes use tiny positive p,
        # so q can be huge even though the physical ternary concentration is 0.
        scale = np.maximum(q, np.maximum(e0, t0))
        en, tn, qn = e0/scale, t0/scale, q/scale
        disc = np.sqrt((en-tn)**2 + 2*qn*(en+tn) + qn*qn)
        c = (2*en*t0) / (en+tn+qn+disc)
        e = (e0 - c) / (1 + p / ke)
        t = (t0 - c) / (1 + p / kt)
        ep, pt = e * p / ke, t * p / kt
        return p, e, t, ep, pt, c

    @classmethod
    def scalar(cls, p0, e0, t0, ke, kt, alpha):
        """Independent 1D Brent solution used for validation and fallback."""
        cls.validate_inputs(p0, e0, t0, ke, kt, alpha)
        if p0 == 0:
            return np.array([0., e0, t0, 0., 0., 0.])
        lower = p0 / (1 + e0/ke + t0/kt + alpha*e0*t0/(ke*kt))
        def residual(lp):
            z = cls.fixed_free(np.exp(lp), e0, t0, ke, kt, alpha)
            return np.log((z[0]+z[3]+z[4]+z[5])/p0)
        lo, hi = np.log(lower) - 1e-8, np.log(p0) + 1e-8
        lp = brentq(residual, lo, hi, xtol=1e-12, rtol=1e-14)
        return np.asarray(cls.fixed_free(np.exp(lp), e0, t0, ke, kt, alpha), float)

    @classmethod
    def batch(cls, p0, e0, t0, ke, kt, alpha):
        """Vectorized log-space bisection of the same exact mass balances.

        Avoids thousands of 3D solves inside a time integrator. A tight
        fixed bisection count is independently cross-checked in validation.
        """
        p0, e0, t0, alpha = np.broadcast_arrays(p0, e0, t0, alpha)
        safe = np.maximum(p0, 1e-300)
        lo = np.log(safe / (1 + e0/ke + t0/kt + alpha*e0*t0/(ke*kt))) - 1e-8
        hi = np.log(safe) + 1e-8
        for _ in range(55):
            mid = (lo+hi)/2
            z = cls.fixed_free(np.exp(mid), e0, t0, ke, kt, alpha)
            above = z[0]+z[3]+z[4]+z[5] > p0
            hi = np.where(above, mid, hi)
            lo = np.where(above, lo, mid)
        c = cls.fixed_free(np.exp((lo+hi)/2), e0, t0, ke, kt, alpha)[5]
        return np.where(p0 > 0, c, 0.)

    def solve(self, p0, e0, t0, ke, kt, alpha):
        self.validate_inputs(p0, e0, t0, ke, kt, alpha)
        if min(p0, e0, t0) == 0:
            return self.scalar(p0, e0, t0, ke, kt, alpha)
        logtot = np.log([p0, e0, t0])
        lke, lkt, la = np.log([ke, kt, alpha])
        def logs(x):
            p, e, t = x
            return np.array([p, e, t, e+p-lke, t+p-lkt, la+e+p+t-lke-lkt])
        def fun(x):
            z = logs(x)
            return np.array([logsumexp(z[[0,3,4,5]]), logsumexp(z[[1,3,5]]), logsumexp(z[[2,4,5]])]) - logtot
        # Uncooperative binary estimates are only a starting point, never a result.
        pguess = p0 / (1+e0/ke+t0/kt)
        x0 = np.log([pguess, e0/(1+pguess/ke), t0/(1+pguess/kt)])
        accepted = None
        for method in ("hybr", "lm"):
            options = {"xtol": 1e-10, "maxfev": 1000} if method == "hybr" else {"ftol": 1e-12, "xtol": 1e-12, "maxiter": 2000}
            ans = root(fun, x0, method=method, options=options)
            if np.all(np.isfinite(ans.x)) and np.max(np.abs(fun(ans.x))) < 2e-9:
                candidate = np.exp(logs(ans.x))
                if candidate[5] <= min(p0,e0,t0)*(1+1e-8):
                    accepted = candidate
                    self.counts[method] += 1
                    break
        if accepted is None:
            accepted = self.scalar(p0,e0,t0,ke,kt,alpha)
            self.counts["scalar_fallback"] += 1
        z = accepted
        sums = np.array([z[0]+z[3]+z[4]+z[5], z[1]+z[3]+z[5], z[2]+z[4]+z[5]])
        error = float(np.max(np.abs(sums/np.array([p0,e0,t0])-1)))
        self.max_relative_balance_error = max(self.max_relative_balance_error, error)
        if error > 1e-8 or not np.all(np.isfinite(z)) or np.min(z) < 0:
            raise ArithmeticError(f"Equilibrium validation failed: {error=}")
        return z


def write_csv(path, rows):
    rows = list(rows)
    if not rows:
        raise ValueError(f"Refusing to write empty table: {path}")
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def dump_json(path, value):
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2, allow_nan=False)+"\n", encoding="utf-8")


def exact_optimum(e0, t0, ke, kt, alpha):
    pf = math.sqrt(ke*kt)
    z = np.asarray(Equilibrium.fixed_free(pf,e0,t0,ke,kt,alpha),float)
    return float(z[0]+z[3]+z[4]+z[5]), float(z[5])


def threshold_window(fn, peak_log, peak_y, fraction, bounds=(-3.,6.)):
    def g(x):
        return fn(x) - fraction*peak_y
    # None means the edge was not bracketed in the requested concentration range.
    lower = 10**brentq(g,bounds[0],peak_log) if g(bounds[0]) < 0 else None
    upper = 10**brentq(g,peak_log,bounds[1]) if g(bounds[1]) < 0 else None
    return lower, upper


def equilibrium_profiles(cfg, engine, out):
    doses = np.logspace(-3,6,cfg.points)  # nM = 1e-12 to 1e-3 M
    data, metrics, rows = {}, [], []
    for alpha in ALPHAS:
        species = np.array([engine.solve(p,cfg.e_total_nm,cfg.t_total_nm,cfg.kd_e_nm,cfg.kd_t_nm,alpha) for p in doses])
        data[alpha] = species
        def fn(x):
            return engine.scalar(10**x,cfg.e_total_nm,cfg.t_total_nm,cfg.kd_e_nm,cfg.kd_t_nm,alpha)[5]
        opt = minimize_scalar(lambda x:-fn(x),bounds=(-3,6),method="bounded",options={"xatol":1e-10})
        if not opt.success:
            raise ArithmeticError("Peak optimizer failed")
        exact_p, exact_c = exact_optimum(cfg.e_total_nm,cfg.t_total_nm,cfg.kd_e_nm,cfg.kd_t_nm,alpha)
        lo, hi = threshold_window(fn,opt.x,-opt.fun,.8)
        metrics.append(dict(alpha=alpha,peak_total_p_nm=float(10**opt.x),peak_ept_nm=float(-opt.fun),
                            exact_peak_total_p_nm=exact_p,exact_peak_ept_nm=exact_c,
                            supplied_formula_p_nm=math.sqrt((cfg.kd_e_nm+cfg.e_total_nm)*(cfg.kd_t_nm+cfg.t_total_nm)),
                            window80_low_nm=lo,window80_high_nm=hi,high_dose_ept_nm=float(species[-1,5])))
        for p,z in zip(doses,species):
            row = {"alpha":alpha,"P_total_M":p*1e-9,"P_total_nM":p}
            row.update(dict(zip(("P_free_nM","E_free_nM","T_free_nM","EP_nM","PT_nM","EPT_nM"),z)))
            rows.append(row)
        LOG.info("alpha=%g | peak EPT=%.6f nM | optimal total P=%.6f nM | 80%% window=%s to %s nM",alpha,-opt.fun,10**opt.x,lo,hi)
    write_csv(out/"data_task2"/"equilibrium_species.csv", rows)
    write_csv(out/"data_task2"/"equilibrium_metrics.csv",metrics)
    return doses,data,metrics


def linker_ensembles(cfg, out):
    # Atom maps specify attachment-point proxies, NOT real E3/POI warheads.
    # Similar contour lengths do not imply a matched medicinal-chemistry pair.
    designs = {
        "Flexible PEG": "[CH3:1]COCCOCCOC[CH3:2]",
        "Rigid alkynyl": "[CH3:1]C#CC#CC#C[CH3:2]",
    }
    arrays, summaries, allrows = {}, [], []
    for name,smiles in designs.items():
        mol = Chem.AddHs(Chem.MolFromSmiles(smiles))
        anchors = [next(a.GetIdx() for a in mol.GetAtoms() if a.GetAtomMapNum()==m) for m in (1,2)]
        heavy = [a.GetIdx() for a in mol.GetAtoms() if a.GetAtomicNum()>1]
        linker_atoms = [a for a in heavy if a not in anchors]
        params = AllChem.ETKDGv3()
        params.randomSeed = cfg.seed
        params.numThreads = 1
        params.pruneRmsThresh = -1.0  # Exactly 100 draws; duplicates retained and disclosed.
        ids = list(AllChem.EmbedMultipleConfs(mol,numConfs=cfg.conformers,params=params))
        if len(ids) != cfg.conformers:
            raise RuntimeError(f"{name}: expected {cfg.conformers} conformers, embedded {len(ids)}")
        if not AllChem.MMFFHasAllMoleculeParams(mol):
            raise RuntimeError(f"MMFF94s parameters unavailable for {name}")
        results = AllChem.MMFFOptimizeMoleculeConfs(mol,numThreads=1,maxIters=3000,mmffVariant="MMFF94s")
        coords, rg, distances, energies = [], [], [], []
        stem = name.lower().replace(" ","_")
        writer = Chem.SDWriter(str(out/"data_task2"/(stem+"_conformers.sdf")))
        try:
            for cid,(status,energy) in zip(ids,results):
                if status != 0:
                    status = AllChem.MMFFOptimizeMolecule(mol,maxIters=10000,mmffVariant="MMFF94s",confId=cid)
                    props = AllChem.MMFFGetMoleculeProperties(mol,mmffVariant="MMFF94s")
                    energy = AllChem.MMFFGetMoleculeForceField(mol,props,confId=cid).CalcEnergy()
                if status != 0:
                    raise RuntimeError(f"{name} conformer {cid}: MMFF did not converge")
                xyz = np.array(mol.GetConformer(cid).GetPositions())
                dist = float(np.linalg.norm(xyz[anchors[0]]-xyz[anchors[1]]))
                # RDKit mass-weighted Rg includes explicit hydrogens.
                radius = float(rdMolDescriptors.CalcRadiusOfGyration(mol,confId=cid))
                coords.append(xyz[heavy]-xyz[heavy].mean(axis=0))
                rg.append(radius); distances.append(dist); energies.append(float(energy))
                mol.SetProp("_Name",f"{name} synthetic attachment-point proxy {cid}")
                for key,value in {"anchor_atom_maps":"1,2","distance_A":dist,"Rg_A":radius,"energy_kcal_mol":energy,"ensemble":"ETKDGv3 unweighted sampling; not a thermodynamic population"}.items():
                    mol.SetProp(key,str(value))
                writer.write(mol,confId=cid)
                allrows.append(dict(linker=name,conformer_id=cid,distance_A=dist,Rg_A=radius,energy_kcal_mol=energy,mmff_status=status))
        finally:
            writer.close()
        xyzs = np.asarray(coords)
        ref = xyzs[0]
        # Iterative generalized Procrustes alignment removes translation/rotation.
        for _ in range(30):
            aligned = []
            for xyz in xyzs:
                u,_,vt = np.linalg.svd(xyz.T@ref)
                rot = u@np.diag([1.,1.,np.linalg.det(u@vt)])@vt
                aligned.append(xyz@rot)
            aligned = np.array(aligned)
            mean = aligned.mean(axis=0)
            if np.max(np.abs(ref-mean)) < 1e-8:
                break
            ref = mean
        per_atom = np.sqrt(np.mean(np.sum((aligned-mean)**2,axis=2),axis=0))
        loc = [heavy.index(idx) for idx in linker_atoms]
        rmsf = float(np.sqrt(np.mean(per_atom[loc]**2)))
        ds,rs = np.array(distances),np.array(rg)
        fraction = float(np.mean((ds>=cfg.compatible_low_a)&(ds<=cfg.compatible_high_a)))
        summary = dict(linker=name,smiles=smiles,conformers=len(ids),mean_distance_A=float(ds.mean()),
                       distance_sd_A=float(ds.std(ddof=1)),linker_RMSF_A=rmsf,mean_Rg_A=float(rs.mean()),
                       compatible_fraction=fraction,mmff_converged=len(ids))
        summaries.append(summary)
        arrays[name] = dict(distances=ds,rg=rs,rmsf=per_atom)
        write_csv(out/"data_task2"/(stem+"_atom_rmsf.csv"),
                  [dict(atom_index=idx,is_anchor=idx in anchors,RMSF_A=float(v)) for idx,v in zip(heavy,per_atom)])
        LOG.info("%s | n=%d | r=%.4f +/- %.4f A | linker RMSF=%.4f A | Rg=%.4f A | illustrative compatibility=%.1f%%",
                 name,len(ids),ds.mean(),ds.std(ddof=1),rmsf,rs.mean(),100*fraction)
    write_csv(out/"data_task2"/"linker_conformers.csv",allrows)
    write_csv(out/"data_task2"/"linker_summary.csv",summaries)
    return arrays,summaries


def simulate(cfg,doses,alphas,rtol=2e-7,atol=1e-9,t_eval=None):
    doses,alphas = np.broadcast_arrays(np.asarray(doses,float),np.asarray(alphas,float))
    shape = doses.shape
    ds,aa = doses.ravel(),alphas.ravel()
    def rhs(_,log_fraction):
        target = cfg.t_total_nm*np.exp(log_fraction)
        c = Equilibrium.batch(ds,cfg.e_total_nm,target,cfg.kd_e_nm,cfg.kd_t_nm,aa)
        loss = cfg.vmax_nm_h*c/(cfg.km_nm+c)
        # Constant synthesis restores the untreated baseline if turnover > 0.
        return (cfg.basal_turnover_h*(cfg.t_total_nm-target)-loss)/target
    sol = solve_ivp(rhs,(0.,cfg.hours),np.zeros(ds.size),method="DOP853",rtol=rtol,atol=atol,t_eval=t_eval)
    if not sol.success or not np.all(np.isfinite(sol.y)):
        raise ArithmeticError("Degradation integration failed: "+sol.message)
    fractions = np.exp(sol.y).reshape(shape+(sol.t.size,))
    if np.min(fractions)<0 or np.max(fractions)>1+1e-8:
        raise ArithmeticError("Target fraction outside physical range")
    return sol.t,fractions


def degradation_profiles(cfg,doses,out):
    times = np.linspace(0,cfg.hours,97)
    times,fractions = simulate(cfg,doses[None,:],np.array(ALPHAS)[:,None],t_eval=times)
    metrics=[]
    for k,alpha in enumerate(ALPHAS):
        def fn(logp):
            _,ys=simulate(cfg,[10**logp],[alpha])
            return float(100*(1-ys[0,-1]))
        opt=minimize_scalar(lambda x:-fn(x),bounds=(-3,6),method="bounded",options={"xatol":2e-5})
        if not opt.success:
            raise ArithmeticError("Degradation peak optimization failed")
        low,high=threshold_window(fn,opt.x,-opt.fun,.5)
        metrics.append(dict(alpha=alpha,Dmax_pct=float(-opt.fun),DC50_low_nM=low,DC50_high_nM=high,
                            optimal_degradation_dose_nM=float(10**opt.x),time_h=cfg.hours))
        LOG.info("Synthetic assay alpha=%g | Dmax=%.5f%% | ascending DC50=%s nM | hook-side crossing=%s nM",alpha,-opt.fun,low,high)
    write_csv(out/"data_task2"/"degradation_metrics.csv",metrics)
    write_csv(out/"data_task2"/"degradation_timecourses.csv",
              (dict(alpha=alpha,P_total_nM=p,time_h=t,target_fraction=float(fractions[a,i,j]),degradation_pct=float(100*(1-fractions[a,i,j])))
               for a,alpha in enumerate(ALPHAS) for i,p in enumerate(doses) for j,t in enumerate(times)))
    # Readout models: HiBiT linear in remaining target plus explicit background.
    # Noise is added to readout only; mechanistic endpoints remain noise free.
    idx=2
    rng=np.random.default_rng(cfg.seed)
    endpoint=fractions[idx,:,-1]
    raw_mean=500+100000*endpoint
    raw=rng.normal(raw_mean[:,None],(0.03*raw_mean+100)[:,None],size=(len(doses),3))
    observed=100*(1-(raw-500)/100000)
    sem=observed.std(axis=1,ddof=1)/math.sqrt(3)
    mask=doses<=metrics[idx]["optimal_degradation_dose_nM"]
    dmax=metrics[idx]["Dmax_pct"]
    # Conditional rising-limb Hill fit: plateau fixed to mechanistic Dmax.
    # A single monotone Hill curve is never fitted across the descending limb.
    def hill(x,params):
        logdc,h=params
        return dmax*expit(h*(np.log(x)-logdc))
    fitted=least_squares(lambda pars:(hill(doses[mask],pars)-observed[mask].mean(axis=1))/np.maximum(sem[mask],0.5),
                         [np.log(metrics[idx]["DC50_low_nM"] or doses[0]),1.],
                         bounds=([np.log(1e-6),.05],[np.log(1e9),8.]),max_nfev=3000)
    if not fitted.success:
        raise ArithmeticError("Ascending-limb Hill fit failed")
    fit=dict(alpha=10.,DC50_hill_nM=float(np.exp(fitted.x[0])),hill_slope=float(fitted.x[1]),
             Dmax_fixed_pct=dmax,fit_points=int(mask.sum()),
             rising_limb_RMSE_pct=float(np.sqrt(np.mean((hill(doses[mask],fitted.x)-observed[mask].mean(axis=1))**2))),
             note="Conditional empirical rising-limb fit; Dmax fixed to mechanistic maximum; no descending-limb extrapolation")
    dump_json(out/"data_task2"/"hibit_hill_fit.json",fit)
    write_csv(out/"data_task2"/"synthetic_hibit_replicates.csv",
              (dict(P_total_nM=p,replicate=r+1,raw_RLU=float(raw[i,r]),background_RLU=500,
                    untreated_signal_RLU=100000,degradation_pct=float(observed[i,r]),is_rising_limb=bool(mask[i]))
               for i,p in enumerate(doses) for r in range(3)))
    LOG.info("HiBiT ascending Hill fit | DC50=%.5f nM | h=%.4f | RMSE=%.4f percentage points",fit["DC50_hill_nM"],fit["hill_slope"],fit["rising_limb_RMSE_pct"])
    return times,fractions,metrics,observed,sem,fit,mask


def save_figure(fig,path):
    fig.savefig(path,dpi=300,facecolor="white",bbox_inches="tight",metadata={"Software":"Task 2 reproducible synthetic TPD model"})
    plt.close(fig)


def make_figures(cfg,out,doses,eq,em,linkers,lm,assay):
    plt.rcParams.update({"font.family":"DejaVu Sans","font.size":10,"axes.spines.top":False,
                         "axes.spines.right":False,"axes.titleweight":"bold","axes.labelcolor":"#233448",
                         "text.color":"#233448","axes.grid":True,"grid.alpha":.16,"savefig.dpi":300})
    figs=out/"figures_task2"
    fig,axes=plt.subplots(1,2,figsize=(12,4.8),layout="constrained")
    for alpha,color,m in zip(ALPHAS,COLORS,em):
        axes[0].plot(doses*1e-9,eq[alpha][:,5],color=color,lw=2.3,label=rf"$\alpha={alpha:g}$")
        axes[0].plot(m["peak_total_p_nm"]*1e-9,m["peak_ept_nm"],"o",color=color,ms=4)
        if m["window80_low_nm"] and m["window80_high_nm"]:
            axes[1].plot(np.array([m["window80_low_nm"],m["window80_high_nm"]])*1e-9,[alpha,alpha],color=color,lw=8,solid_capstyle="round")
            axes[1].plot(m["peak_total_p_nm"]*1e-9,alpha,"o",mfc="white",mec=color,ms=7)
    axes[0].set(xscale="log",xlabel="Total PROTAC concentration (M)",ylabel="Ternary complex [EPT] (nM)",title="A  Mass-action hook effect")
    axes[0].legend(frameon=False)
    axes[1].set(xscale="log",yscale="log",xlabel="Total PROTAC concentration (M)",ylabel=r"Cooperativity $\alpha$",title="B  Window at 80% of each peak")
    axes[1].set_yticks(ALPHAS,labels=[str(a) for a in ALPHAS])
    fig.suptitle("Cooperativity increases peak height and broadens the window",fontsize=15)
    save_figure(fig,figs/"fig1_ternary_hook_effect_curves.png")

    kds=np.logspace(-1,3,cfg.heatmap_points)
    ke,kt=np.meshgrid(kds,kds)
    heatrows=[]
    matrices=[]
    for alpha in ALPHAS:
        pf=np.sqrt(ke*kt)
        z=Equilibrium.fixed_free(pf,cfg.e_total_nm,cfg.t_total_nm,ke,kt,alpha)
        matrices.append(z[5])
        heatrows.extend(dict(alpha=alpha,Kd_E_nM=float(ke[j,i]),Kd_T_nM=float(kt[j,i]),
                             peak_EPT_nM=float(z[5][j,i]),optimal_total_P_nM=float((z[0]+z[3]+z[4]+z[5])[j,i]))
                        for j in range(len(kds)) for i in range(len(kds)))
    write_csv(out/"data_task2"/"affinity_cooperativity_heatmap.csv",heatrows)
    fig,axes=plt.subplots(2,2,figsize=(10,8),layout="constrained")
    norm=LogNorm(vmin=min(x.min() for x in matrices),vmax=min(cfg.e_total_nm,cfg.t_total_nm))
    for ax,alpha,mat in zip(axes.ravel(),ALPHAS,matrices):
        mesh=ax.pcolormesh(kds,kds,mat,norm=norm,cmap="viridis",shading="auto",rasterized=True)
        ax.set(xscale="log",yscale="log",xlabel=r"$K_{D,E}$ (nM)",ylabel=r"$K_{D,T}$ (nM)",title=rf"$\alpha={alpha:g}$")
        ax.grid(False)
    fig.colorbar(mesh,ax=axes.ravel().tolist(),label="Maximum [EPT] over total PROTAC (nM)",shrink=.83)
    fig.suptitle("Affinity sensitivity at four cooperativity regimes",fontsize=15)
    save_figure(fig,figs/"fig2_cooperativity_alpha_heatmap.png")

    fig,axes=plt.subplots(1,2,figsize=(12,4.8),layout="constrained")
    all_d=np.concatenate([x["distances"] for x in linkers.values()])
    bins=np.linspace(min(2.,all_d.min()-.3),max(14.,all_d.max()+.3),31)
    for (name,x),color,m in zip(linkers.items(),(COLORS[1],COLORS[3]),lm):
        axes[0].hist(x["distances"],bins=bins,weights=np.ones(cfg.conformers)/cfg.conformers,alpha=.65,color=color,label=name)
        axes[1].scatter(x["distances"],x["rg"],s=20,alpha=.55,color=color,label=f"{name}; RMSF={m['linker_RMSF_A']:.2f} A")
    axes[0].axvspan(cfg.compatible_low_a,cfg.compatible_high_a,color="#008F83",alpha=.1,label="Illustrative compatible window")
    axes[0].set(xlabel="Attachment-point proxy distance (angstrom)",ylabel="Fraction per bin",title="A  Unweighted ETKDGv3 samples")
    axes[1].set(xlabel="Attachment-point proxy distance (angstrom)",ylabel="Mass-weighted radius of gyration (angstrom)",title="B  Compactness and aligned linker RMSF")
    for ax in axes: ax.legend(frameon=False,fontsize=8)
    fig.suptitle(f"{cfg.conformers} conformers per linker | capped fragments; no protein geometry",fontsize=14)
    save_figure(fig,figs/"fig3_linker_conformational_histogram.png")

    times,fracs,dm,observed,sem,fit,mask=assay
    fig=plt.figure(figsize=(13,9),layout="constrained")
    gs=fig.add_gridspec(2,2,height_ratios=(.8,1.2))
    axb=fig.add_subplot(gs[0,:]); axd=fig.add_subplot(gs[1,0]); axt=fig.add_subplot(gs[1,1])
    lane_doses=np.r_[0.,np.logspace(-3,6,13)]
    _,bands=simulate(cfg,lane_doses,np.full(lane_doses.size,10.))
    levels=bands[:,-1]
    rng=np.random.default_rng(cfg.seed+1)
    h,w=125,len(lane_doses)*65
    yy,xx=np.mgrid[:h,:w]
    gel=np.full((h,w),.965)+rng.normal(0,.004,(h,w))
    for i,intensity in enumerate(levels):
        profile=np.exp(-((xx-(i+.5)*65)/21)**6)
        gel-=.78*intensity*profile*np.exp(-.5*((yy-37)/5)**2)
        gel-=.62*profile*np.exp(-.5*((yy-88)/5)**2)
    axb.imshow(np.clip(gel,0,1),cmap="gray",vmin=0,vmax=1,aspect="auto")
    axb.set_xticks((np.arange(len(lane_doses))+.5)*65,labels=["Vehicle"]+[f"{x:g}" for x in lane_doses[1:]],fontsize=8)
    axb.set_yticks([37,88],labels=["POI","Loading control"])
    axb.set_xlabel("Total PROTAC (nM)")
    axb.set_title(f"A  SYNTHETIC Western blot | alpha=10 | {cfg.hours:g} h")
    axb.grid(False)
    for spine in axb.spines.values(): spine.set_visible(False)
    write_csv(out/"data_task2"/"synthetic_western_lanes.csv",[dict(lane=i+1,P_total_nM=p,POI_intensity=float(v),loading_control=1.) for i,(p,v) in enumerate(zip(lane_doses,levels))])
    axd.errorbar(doses[::3]*1e-9,observed[::3].mean(axis=1),yerr=sem[::3],fmt=".",color="#8091A0",alpha=.7,label="Synthetic HiBiT mean +/- SEM (n=3)")
    axd.plot(doses*1e-9,100*(1-fracs[2,:,-1]),color=COLORS[2],lw=2,label="Dynamic mass-action model")
    hill=fit["Dmax_fixed_pct"]*expit(fit["hill_slope"]*(np.log(doses[mask])-np.log(fit["DC50_hill_nM"])))
    axd.plot(doses[mask]*1e-9,hill,"--",color=COLORS[3],lw=2,label="Hill fit: ascending limb only")
    if dm[2]["DC50_low_nM"]:
        axd.axvline(dm[2]["DC50_low_nM"]*1e-9,color=COLORS[2],lw=1,ls=":")
    axd.set(xscale="log",xlabel="Total PROTAC concentration (M)",ylabel="Target degradation (%)",title="B  Biphasic endpoint and conditional Hill fit",ylim=(-8,108))
    axd.legend(frameon=False,fontsize=8,loc="upper left")
    axd.text(.03,.45,f"Dmax = {dm[2]['Dmax_pct']:.1f}%\nDC50 = {dm[2]['DC50_low_nM']:.3g} nM" if dm[2]['DC50_low_nM'] else "DC50 outside range",transform=axd.transAxes,ha="left",fontsize=10)
    for desired in (0.001,1.,100.,1e4,1e6):
        i=int(np.argmin(abs(np.log10(doses)-np.log10(desired))))
        axt.plot(times,100*fracs[2,i,:],lw=2,label=f"{doses[i]:.3g} nM")
    axt.set(xlabel="Time (h)",ylabel="Background-corrected HiBiT (% vehicle)",title="C  Time-dependent target depletion",ylim=(-2,105))
    axt.legend(frameon=False,fontsize=8)
    fig.suptitle("Synthetic assay digital twin | fast binding equilibrium at every time step",fontsize=15)
    save_figure(fig,figs/"fig4_synthetic_western_blot_hibit.png")


def validate_numerics(cfg,engine,em,out):
    rng=np.random.default_rng(cfg.seed)
    errors=[]; batch_errors=[]; thermo_errors=[]
    for _ in range(120):
        p,e,t,ke,kt=10**rng.uniform([-3,-1,-1,-1,-1],[6,3,3,3,3])
        alpha=10**rng.uniform(-2,2)
        z=engine.solve(p,e,t,ke,kt,alpha)
        ref=engine.scalar(p,e,t,ke,kt,alpha)
        errors.append(float(np.max(np.abs(z-ref)/np.maximum(ref,1e-12))))
        bat=float(engine.batch(p,e,t,ke,kt,alpha))
        batch_errors.append(abs(bat-ref[5])/max(ref[5],1e-12))
        thermo_errors.append(abs((z[3]*z[2]/z[5])/(kt/alpha)-1))
        if z[5]>min(p,e,t)*(1+1e-8): raise AssertionError("Stoichiometry bound")
    zero=engine.solve(0,100,100,10,100,10)
    np.testing.assert_array_equal(zero,[0,100,100,0,0,0])
    for p,e,t in [(1,0,100),(1,100,0),(1,0,0)]:
        z=engine.solve(p,e,t,10,100,10)
        np.testing.assert_allclose([z[0]+z[3]+z[4]+z[5],z[1]+z[3]+z[5],z[2]+z[4]+z[5]],[p,e,t],atol=1e-10)
    invalid_rejected=0
    for values in [(-1,100,100,10,100,1),(1,100,100,0,100,1),(1,100,100,10,100,-1),(float("nan"),100,100,10,100,1)]:
        try: engine.solve(*values)
        except ValueError: invalid_rejected+=1
    if invalid_rejected!=4: raise AssertionError("Invalid input accepted")
    if max(errors)>1e-7 or max(batch_errors)>1e-8 or max(thermo_errors)>1e-8:
        raise AssertionError("Independent equilibrium check failed")
    # Validate asymmetric proteins as well: the supplied formula is not general.
    asymmetric=[]
    for e,t,ke,kt in [(100,100,10,100),(20,300,3,70),(100,100,10,10)]:
        for alpha in ALPHAS:
            p,c=exact_optimum(e,t,ke,kt,alpha)
            opt=minimize_scalar(lambda lp:-engine.scalar(10**lp,e,t,ke,kt,alpha)[5],bounds=(-3,6),method="bounded")
            if abs(10**opt.x/p-1)>2e-4: raise AssertionError("Exact optimum mismatch")
            asymmetric.append(dict(E_total_nM=e,T_total_nM=t,Kd_E_nM=ke,Kd_T_nM=kt,alpha=alpha,exact_opt_nM=p,numeric_opt_nM=10**opt.x))
    ds=np.array([0.,.001,1.,100.,1e4,1e6])
    _,y1=simulate(cfg,ds,np.full(6,10.))
    _,y2=simulate(cfg,ds,np.full(6,10.),rtol=2e-9,atol=1e-11)
    ode_diff=float(np.max(abs(y1[:,-1]-y2[:,-1])))
    if ode_diff>2e-5 or abs(y1[0,-1]-1)>1e-10:
        raise AssertionError("ODE tolerance convergence or vehicle control failed")
    high_hook=all(m["high_dose_ept_nm"]<m["peak_ept_nm"] for m in em)
    if not high_hook: raise AssertionError("Hook not resolved in default dose range")
    result=dict(status="PASS",random_equilibrium_cases=120,invalid_input_cases_rejected=invalid_rejected,
                max_root_vs_brent_relative_error=max(errors),max_batch_vs_brent_relative_error=max(batch_errors),
                max_thermodynamic_cycle_relative_error=max(thermo_errors),
                max_relative_mass_balance_error=engine.max_relative_balance_error,
                ode_tighter_tolerance_max_fraction_difference=ode_diff,
                all_four_regimes_show_high_dose_hook=high_hook,solver_counts=engine.counts,
                asymmetric_peak_checks=asymmetric)
    dump_json(out/"validation_task2.json",result)
    LOG.info("VALIDATION PASS | max mass-balance error=%.3g | root/Brent=%.3g | batch/Brent=%.3g | ODE tolerance difference=%.3g",engine.max_relative_balance_error,max(errors),max(batch_errors),ode_diff)
    return result


def value(x):
    return "outside range" if x is None else f"{x:.6g}"


def write_reports(cfg,out,em,lm,dm,fit,validation):
    eqtable="| alpha | Peak EPT (nM) | Optimal total P (nM) | 80% low (nM) | 80% high (nM) |\n|---:|---:|---:|---:|---:|\n"+"\n".join(f"| {m['alpha']:g} | {m['peak_ept_nm']:.6g} | {m['peak_total_p_nm']:.6g} | {value(m['window80_low_nm'])} | {value(m['window80_high_nm'])} |" for m in em)
    dtable="| alpha | Dmax (%) | DC50 rising (nM) | Half-max hook-side (nM) | Optimal endpoint dose (nM) |\n|---:|---:|---:|---:|---:|\n"+"\n".join(f"| {m['alpha']:g} | {m['Dmax_pct']:.6g} | {value(m['DC50_low_nM'])} | {value(m['DC50_high_nM'])} | {m['optimal_degradation_dose_nM']:.6g} |" for m in dm)
    ltable="| Linker | n | Mean r (A) | SD r (A) | Linker RMSF (A) | Mean Rg (A) | Compatible fraction |\n|---|---:|---:|---:|---:|---:|---:|\n"+"\n".join(f"| {m['linker']} | {m['conformers']} | {m['mean_distance_A']:.4f} | {m['distance_sd_A']:.4f} | {m['linker_RMSF_A']:.4f} | {m['mean_Rg_A']:.4f} | {m['compatible_fraction']:.2%} |" for m in lm)
    equations=r"""
$$EP=ep/K_E,\quad PT=tp/K_T,\quad C=EPT=\alpha ept/(K_EK_T).$$
$$P_0=p+EP+PT+C,\quad E_0=e+EP+C,\quad T_0=t+PT+C.$$
$$K_{D,ET}=K_T/\alpha,\qquad K_{D,TE}=K_E/\alpha.$$
$$q(p)=\frac{(K_E+p)(K_T+p)}{\alpha p},\quad Cq=(E_0-C)(T_0-C).$$
$$C(p)=\frac{2E_0T_0}{E_0+T_0+q+\sqrt{(E_0-T_0)^2+2q(E_0+T_0)+q^2}}.$$
$$P_0(p)=p+(E_0-C)\frac{p}{K_E+p}+(T_0-C)\frac{p}{K_T+p}+C.$$
$$p_* = \sqrt{K_EK_T},\quad
P_{0,*}=\sqrt{K_EK_T}+\frac{E_0\sqrt{K_T}+T_0\sqrt{K_E}}{\sqrt{K_E}+\sqrt{K_T}}.$$
"""
    figures="\n\n".join(f"![Figure {i}](figures_task2/{name})" for i,name in enumerate([
        "fig1_ternary_hook_effect_curves.png","fig2_cooperativity_alpha_heatmap.png",
        "fig3_linker_conformational_histogram.png","fig4_synthetic_western_blot_hibit.png"],1))
    params=f"E0={cfg.e_total_nm:g} nM; T0={cfg.t_total_nm:g} nM; Kd,E={cfg.kd_e_nm:g} nM; Kd,T={cfg.kd_t_nm:g} nM; Vmax={cfg.vmax_nm_h:g} nM/h; Km={cfg.km_nm:g} nM; endpoint={cfg.hours:g} h; basal turnover={cfg.basal_turnover_h:g} /h; seed={cfg.seed}."
    en=f"""# Task 2: TPD ternary cooperativity and hook-effect modeling

## Scope and reproducibility

This is an executable, synthetic biophysical model, not a validated predictor of a specific degrader or a clinical dosing tool. No measured affinity, protein structure, calibrated assay, or full PROTAC structure was supplied. The selected defaults are illustrative: {params} The requested protein levels are modeling assumptions, not universal intracellular abundances. All internal concentrations are nM (1 nM = 1e-9 M), time is hours, and conformer distances are angstroms. The dose sweep covers 1e-12–1e-3 M, including concentrations that should not be interpreted as feasible cellular exposures.

Run `python run_task2_tpd_ternary_cooperativity.py`; use `--help` for parameters. The single file regenerates all four 300 DPI figures, both reports, CSV/SDF records, validation, dependency versions, checksums and logging. Dependencies are NumPy, SciPy, Matplotlib and RDKit; no network calls or external templates are needed. Seeds and single-thread conformer embedding make repeated runs reproducible within the recorded environment. Different RDKit releases may produce different conformers. Software versions and file hashes are recorded in `manifest_task2.json`.

## Event-driven pharmacology

An occupancy-driven inhibitor generally needs sustained engagement to suppress target function. A degrader can instead recruit an E3 ligase and initiate a ubiquitination event, after which target removal can outlast an individual binding event. Structural studies show that induced contacts between the recruited proteins contribute to cooperative recognition [3]. Binding remains necessary, but equilibrium ternary abundance alone does not establish productive ubiquitination, proteasomal processing, permeability or selectivity. The present equations assume all ternary complex contributes equally to an effective degradation flux; catalytic PROTAC recycling and fixed E3 total are explicit assumptions.

## Mass-action derivation and the correct optimum

Lowercase p, e, t denote free concentrations. K_E and K_T are the binary dissociation constants. Alpha is a supplied thermodynamic parameter, not inferred from linker geometry. The two ternary association paths obey the same thermodynamic cycle.
{equations}

This derivation is included explicitly so the script can be audited independently of published three-body frameworks [1,2]. At fixed free p, eliminating e and t gives a quadratic in C. The rationalized smaller root above avoids cancellation. The total-to-free mapping is monotonically increasing for this stable equilibrium binding network; therefore maximizing C in free p also locates its maximum in total P. Since q=(p+K_E+K_T+K_E K_T/p)/alpha, q is minimized at p=sqrt(K_E K_T). At that point the two binary occupancy fractions sum to one, so the coefficient of C in P0 cancels. The **optimal total P is independent of alpha**, although peak height and threshold-window width are not.

The requested expression sqrt((K_E+E0)(K_T+T0)) is retained in the exported table as `supplied_formula_p_nm`; it is not used as a general identity. Here it gives **{em[0]['supplied_formula_p_nm']:.6g} nM**, versus the exact **{em[0]['exact_peak_total_p_nm']:.6g} nM**, with free optimum **{math.sqrt(cfg.kd_e_nm*cfg.kd_t_nm):.6g} nM**. They coincide in the fully symmetric special case K_E=K_T and E0=T0. Asymmetric-protein test cases in the validation file establish why the distinction matters.

At p approaching zero, C ~ alpha E0 T0 p/(K_E K_T), and rises from zero. At sufficiently large p, C ~ alpha E0 T0/p, while EP and PT approach their respective protein totals. Thus every finite positive alpha in this **two-binary-arm model** eventually exhibits a hook. A high-alpha curve is a cooperative PROTAC scenario; it is not a mechanistically complete molecular-glue model. A glue with negligible binding to one free protein, or a pre-existing protein-protein complex, requires a different reaction network. Neither a universal hook for all molecular glues nor an obligatory hook inside every experimental dose range follows from these equations.

{eqtable}

The 80% windows refer to each curve's own maximum, not a common efficacy threshold and not a therapeutic window. The heatmaps use the exact maximum over total ligand at each affinity pair (0.1–1000 nM), with four alpha panels and one shared logarithmic color scale. Numerically maximizing each representative curve independently verifies the analytic peak.

## Solver implementation and validation

The main sweep uses `scipy.optimize.root` with hybr, then Levenberg-Marquardt if necessary, in logarithms of the three free concentrations. Residuals are log reconstructed totals minus log specified totals, evaluated using log-sum-exp. This enforces positive species without mixing incompatible scales. Convergence flags are insufficient: mass balance, finiteness and stoichiometric bounds are checked. A separate scalar Brent solution of the eliminated quadratic is the fallback and cross-check. The ODE uses vectorized log-bisection of the same exact mass balances at each time step, with changing target total.

Validation: **{validation['status']}**; {validation['random_equilibrium_cases']} randomized positive systems, zero-dose and zero-protein cases, four invalid-input checks, both equilibrium routes, peak checks with asymmetric proteins, and a tighter-tolerance ODE comparison. Maximum relative mass-balance error: {validation['max_relative_mass_balance_error']:.3e}. Root-versus-Brent species error: {validation['max_root_vs_brent_relative_error']:.3e}. ODE endpoint fraction difference: {validation['ode_tighter_tolerance_max_fraction_difference']:.3e}. These checks support the tested parameter regime; they do not establish the absence of every possible numerical or biological error.

## Linker ensemble and entropy interpretation

The two explicit, capped **linker proxies** are `{lm[0]['smiles']}` and `{lm[1]['smiles']}`. Mapped atoms 1 and 2 define attachment-point positions. These fragments do not contain thalidomide, a VHL binder or a POI warhead; consequently the output is an attachment-point distance, not a measured protein-to-protein distance. Real warheads and protein structures are required to define exit-vector orientations and steric compatibility. The implementation chooses a rigid alkynyl example; piperazine chemistry is not modeled.

Each design receives {cfg.conformers} ETKDGv3 samples with explicit hydrogens and MMFF94s minimization. RMS pruning is disabled to preserve the requested sample count; repeated or symmetry-related minima are retained. These are algorithmic samples, not {cfg.conformers} guaranteed distinct conformers or a Boltzmann population. Nonconverged force-field calculations are retried and then cause a hard failure. Every conformer and its energy are exported as SDF and CSV.

After iterative least-squares heavy-atom superposition, per-atom RMSF is sqrt(mean_k ||x_ki-mean_k x_ki||²). The summary is the root mean square of those RMSFs over non-anchor linker heavy atoms. Rg is mass-weighted over all explicit atoms. Distance SD is a separate statistic and is not substituted for atomic RMSF. The fixed {cfg.compatible_low_a:g}–{cfg.compatible_high_a:g} A window is illustrative and was not tuned to the observed distribution.

{ltable}

Rigidification can reduce the number of accessible unbound conformations, but can also lock an unfavorable geometry. A compatible-state probability p_comp would imply a geometric selection cost -RT ln(p_comp) only if sampled populations were thermodynamic and the compatibility criterion adequately represented binding. Those conditions are not met here, so the script does **not** turn histogram widths or sample fractions into binding entropy, alpha, or potency. For an independently measured alpha, the coupling free energy is ΔG_coop=-RT ln(alpha). Positive cooperativity reflects the net balance of conformational restriction, strain, solvation and intermolecular contacts; one distance distribution does not determine it [3,4].

## Synthetic Western blot and HiBiT digital twin

The requested rate law is implemented as dT_total/dt = -Vmax C/(Km+C). The symbol k_deg in a concentration-rate law must have concentration/time units; here it is explicitly named Vmax in nM/h, not a first-order constant. Optional basal turnover adds k_base(T_initial-T_total), representing constant synthesis plus first-order turnover. Its default is zero to reproduce the requested no-synthesis equation. Integration uses log remaining target to preserve positivity and re-equilibrates C as target is consumed. It assumes rapid binding relative to degradation, constant total intracellular PROTAC, immediate recycling, fixed E3 and no drug clearance. At sufficiently long times the no-synthesis model can exhaust target even at weak effective doses; all reported DC50/Dmax values are time-specific.

Dmax is the numerically optimized degradation maximum at {cfg.hours:g} h over the requested concentration range. DC50 is the **ascending** concentration giving half of that maximum, not necessarily 50% absolute target loss. A second crossing on the hook side is reported separately; missing crossings are null/outside range. The optimal dynamic endpoint dose can differ from the initial equilibrium peak because T_total evolves.

{dtable}

HiBiT signal is 500 + 100000 × target fraction RLU. Three synthetic replicates use Gaussian SD = 3% of expected RLU + 100 RLU. Background-corrected normalization uses a known synthetic vehicle signal; noisy values are not clipped. A Hill function is fitted only to the ascending limb for alpha=10, with Dmax fixed to the mechanistic maximum. It is an empirical, conditional fit, not a mechanistic global fit to a bell curve: fitted DC50={fit['DC50_hill_nM']:.6g} nM, Hill slope={fit['hill_slope']:.5g}, and rising-limb RMSE={fit['rising_limb_RMSE_pct']:.5g} percentage points. No confidence interval is claimed from three generated replicates. The full-dose curve is always the dynamic mass-action prediction.

The Western blot is explicitly labeled **SYNTHETIC**, with target-band darkness proportional to remaining target and a constant loading control; vehicle and high-dose recovery are shown. It contains no fabricated claim of an actual experiment. Geometry sampling and assay kinetics are separate sensitivity modules; no unsupported linker-to-alpha calibration connects them.

## Figures

{figures}

## References

{REFERENCES}
"""
    zh=f"""# 任务二：靶向蛋白降解、三元复合物协同性与钩状效应

## 研究范围与复现

本项目是可执行的合成生物物理模型，不是特定降解剂的经验证预测器，也不提供临床剂量建议。输入未包含实测亲和力、完整 PROTAC、蛋白结构或实验校准数据。默认参数为示例：{params} 100 nM 蛋白总量是任务指定的建模条件，不能代表所有细胞中的生理丰度。内部单位统一为 nM、小时和埃；1 nM=1e-9 M。总 PROTAC 扫描覆盖 1e-12–1e-3 M，共 {cfg.points} 个点；极高浓度不意味着细胞实验中可实现的暴露。

执行 `python run_task2_tpd_ternary_cooperativity.py` 即可再生四张 300 DPI 图、双语报告、CSV 数据、SDF 构象、校验文件、依赖版本、校验和与日志。全部逻辑包含在单个脚本内，不需要网络或外部模板；参数见 `--help`。固定随机种子并单线程构象采样，同一环境下可重复运行；不同 RDKit 版本可能改变构象结果。版本及文件哈希保存在 `manifest_task2.json`。

## 事件驱动与占有率驱动药理学

传统抑制剂通常通过持续占据靶点抑制功能。降解剂则可通过募集 E3、触发泛素化事件并移除靶蛋白，使效应持续时间超过单次结合事件。结构研究展示了被募集蛋白之间的新接触如何参与协同识别 [3]。但“形成三元复合物”并不等价于“必然产生有效降解”：泛素化几何、蛋白酶体处理、细胞通透性及选择性仍需验证。本模型假定全部三元复合物具有相同的有效降解贡献，并显式假设 PROTAC 可即时循环使用、E3 总量不变。

## 质量作用方程、精确解与峰位推导

小写 p、e、t 为游离浓度；K_E、K_T 为二元解离常数；C=[EPT]。alpha 是给定的热力学协同性参数，不能由连接子距离分布直接推断。两条三元形成路径满足同一热力学循环：
{equations}

以上给出了完整代数消元，便于独立核查，并与三体平衡理论框架相衔接 [1,2]。固定游离 p 后可消去 e、t，得到 C 的二次方程；采用有理化的小根避免相近浮点数相减。稳定平衡体系中总浓度随游离浓度单调增加，所以在游离浓度坐标最大化 C 可定位总浓度坐标的峰值。

由于 q=(p+K_E+K_T+K_E K_T/p)/alpha，q 在 p=sqrt(K_E K_T) 时最小。此时两个二元占据分数之和为 1，总浓度式中 C 的系数抵消，得到上式的精确 P0,*。因此该模型中 **alpha 改变峰高和浓度窗口宽度，但不改变平衡峰对应的最优总 PROTAC 浓度**。

任务给出的 sqrt((K_E+E0)(K_T+T0)) 被保留为数据表中的 `supplied_formula_p_nm` 以供比较，不能当作一般恒等式。默认条件下它给出 **{em[0]['supplied_formula_p_nm']:.6g} nM**，而精确总浓度最优值为 **{em[0]['exact_peak_total_p_nm']:.6g} nM**，游离最优值为 **{math.sqrt(cfg.kd_e_nm*cfg.kd_t_nm):.6g} nM**。在 K_E=K_T 且 E0=T0 的完全对称特例中，两者相同。校验文件还包含蛋白总量不对称的案例，避免对称默认条件掩盖公式差异。

当 p 趋近于零，C~alpha E0 T0 p/(K_E K_T)，随浓度上升；当 p 足够大，C~alpha E0 T0/p，同时 EP、PT 趋近各自蛋白总量。因此本模型对任意有限正 alpha 最终均出现钩状效应。但这仅适用于 **两个二元结合臂均存在的反应网络**。alpha=100 表示高度协同的 PROTAC 情景，不能直接代表所有分子胶。缺少可测二元结合臂或存在预形成蛋白互作的分子胶，应使用不同反应网络；不能据此宣称所有分子胶或所有实验浓度区间必有钩状效应。

{eqtable}

80% 窗口按每条曲线自身峰值定义，不是统一效力阈值，也不是治疗窗。亲和力热图在 Kd=0.1–1000 nM 范围内同时变化两个二元亲和力，分别绘制四个 alpha 面板，并共享对数色标。每个格点的最大 EPT 使用精确最优条件计算，而不是粗扫剂量取最大；另用数值寻峰作交叉核对。

## 求解器与数值可靠性

主剂量扫描在三个游离浓度的对数空间使用 `scipy.optimize.root`：先 hybr，再在必要时调用 Levenberg–Marquardt。残差为重建总量的对数与指定总量对数之差，使用 log-sum-exp 稳定求和。接受解之前必须检查质量守恒、非负性、有限性和三元复合物的化学计量上界，不能只信优化器状态码。

独立的一维 Brent 求解器利用消元后的二次解作为备选和交叉验证。ODE 每个时间步采用同一平衡方程的向量化对数二分法，并随靶蛋白总量下降重新求解三元浓度，未把初始 EPT 固定到整个实验终点。

校验结果：**{validation['status']}**。覆盖 {validation['random_equilibrium_cases']} 个随机正参数体系、零剂量、零蛋白、四类非法输入、热力学循环、三种平衡求解路线、非对称体系峰位以及更严格容差的 ODE 复算。最大相对质量守恒误差为 {validation['max_relative_mass_balance_error']:.3e}，多维根与 Brent 的最大物种相对误差为 {validation['max_root_vs_brent_relative_error']:.3e}，ODE 终点靶蛋白比例差为 {validation['ode_tighter_tolerance_max_fraction_difference']:.3e}。这些检验支持已测试的参数范围，不构成对所有数值边界或真实生物过程的无误保证。

## 连接子构象与熵的解释边界

采用柔性 PEG 代理片段 `{lm[0]['smiles']}` 和刚性炔基代理片段 `{lm[1]['smiles']}`，映射原子 1、2 定义连接位点。它们不含沙利度胺、VHL 配体或 POI warhead，因此所测是 **连接位点代理距离**，不是实测蛋白间距。真正的 exit vector 还包含方向；完整 warhead、蛋白结构及空间冲突检查均需要额外输入。刚性示例选择炔基，没有模拟哌嗪。

每种连接子生成 {cfg.conformers} 个显式加氢的 ETKDGv3 样本，并用 MMFF94s 最小化。为满足样本数关闭 RMS 去重，保留重复和对称等价极小值；这不是 {cfg.conformers} 个必然独立构象，也不是平衡玻尔兹曼分布。未收敛的力场优化会重试，仍未收敛则报错。每个样本的结构、距离、Rg、能量与优化状态均导出。

RMSF 在重原子迭代最小二乘叠合、去除平移和旋转后计算：每个原子的 RMSF 为其围绕构象平均位置的均方根偏移，汇总值为非锚点连接子重原子 RMSF 的均方根。距离标准差单独报告，不冒充原子 RMSF。Rg 使用含显式氢的所有原子的质量加权定义。预设的 {cfg.compatible_low_a:g}–{cfg.compatible_high_a:g} 埃兼容窗口仅用于示意，没有按照采样结果调参。

{ltable}

刚性化可能缩小游离态可访问构象集合，但也可能锁定不合适几何。只有在采样概率是热力学概率、几何窗口能代表真实结合兼容性时，才可把 -RT ln(p_comp) 解释为几何选择代价；本采样不满足这些前提。因此脚本不把直方图宽度或兼容比例换算成结合熵、alpha 或效力。独立实验确定的 alpha 可对应 ΔG_coop=-RT ln(alpha)，但它体现构象限制、应变、溶剂化与分子间接触的净效应，不能由一个距离分布决定 [3,4]。

## 合成 Western blot 与 HiBiT 数字孪生

实现 dT_total/dt=-Vmax C/(Km+C)。原任务将浓度变化率中的系数称作 k_deg，其量纲必须是浓度/时间；此处明确使用 Vmax，单位 nM/h，而不是一阶速率常数。可选基础周转项 k_base(T_initial-T_total) 代表恒定合成与一阶周转，默认取零以复现任务的无合成方程。

积分采用剩余靶蛋白比例的对数，保持正值；每一步重新计算平衡。假设结合平衡快于降解、细胞内 PROTAC 总量恒定、无清除、E3 稳定且 PROTAC 即时循环使用。该无合成模型在足够长时间下可能使低有效剂量也耗尽靶蛋白，因此 DC50 和 Dmax 均须附带实验时长。

Dmax 是 {cfg.hours:g} 小时、指定剂量范围内的数值最优降解百分比。DC50 是 **上升支达到 Dmax 一半的浓度**，不一定等于绝对降解 50% 的浓度。钩状效应下降支的半最大交点另列；范围外交点输出 null。由于 T_total 随时间变化，终点最优降解剂量可以不同于初始平衡的 EPT 峰位。

{dtable}

HiBiT 平均信号设为 500+100000×剩余靶蛋白比例 RLU。三次合成重复加入标准差为期望 RLU 的 3% 加 100 RLU 的高斯噪声；以已知背景和合成 vehicle 信号归一化，噪声结果不裁剪。仅对 alpha=10 的上升支拟合 Hill 函数，Dmax 固定为机理模型最大值；这是条件性经验拟合，不是对整条双相曲线强行套用单调 Hill 方程。拟合 DC50={fit['DC50_hill_nM']:.6g} nM，Hill 系数={fit['hill_slope']:.5g}，上升支 RMSE={fit['rising_limb_RMSE_pct']:.5g} 个百分点。没有根据三次合成重复宣称实验置信区间。

Western blot 明确标为 **SYNTHETIC**：POI 条带深度与剩余靶蛋白成比例，内参条带固定，并显示 vehicle 和高剂量信号恢复。图中不存在真实实验记录。连接子构象和降解动力学为独立敏感性模块，没有未经验证的连接子到 alpha 的标定关系。

## 图像

{figures}

## 参考文献

{REFERENCES}
"""
    (out/"TPD_TERNARY_COOPERATIVITY_REPORT_EN.md").write_text(en,encoding="utf-8")
    (out/"TPD_TERNARY_COOPERATIVITY_REPORT_ZH.md").write_text(zh,encoding="utf-8")
    readme=f"""# Task 2 · TPD ternary cooperativity engine

单文件可复现的三元平衡、钩状效应、RDKit 连接子构象与合成降解实验。
Reproducible mass-action equilibrium, linker ensembles and synthetic assay profiling.

## Run

```sh
python -m pip install -r requirements_task2.txt
python run_task2_tpd_ternary_cooperativity.py
```

Python >=3.10. Default output directory is the script's directory; set `--output-dir` to change it. All data are synthetic. No external file is required to generate the reports or figures. `--git-publish` stages only generated Task 2 files in an existing repository, creates the requested commit if needed, and pushes an already-configured upstream. It never invents a remote. A missing repository/upstream returns an explicit error after outputs are generated. Importing the script has no execution side effects.

## Deliverables

| Module | Artifact | Description |
|---|---|---|
| Driver | [Python script](run_task2_tpd_ternary_cooperativity.py) | All four modules, reporting, validation and optional publishing |
| 中文报告 | [中文报告](TPD_TERNARY_COOPERATIVITY_REPORT_ZH.md) | 推导、结果、假设与局限 |
| English report | [English report](TPD_TERNARY_COOPERATIVITY_REPORT_EN.md) | Methods, results and interpretation |
| Validation | [Validation JSON](validation_task2.json) | Independent solvers, mass balances, edge cases, ODE convergence |
| Reproducibility | [Manifest](manifest_task2.json) / [Log](run_task2.log) | Versions, parameters, SHA256, terminal metrics |
| Raw results | [Data directory](data_task2/) | Species, peaks, dose/time curves, readout replicates and SDF conformers |

## Equilibrium master table

{eqtable}

## Synthetic degradation master table

{dtable}

## Linker master table

{ltable}

## Scientific corrections

The general exact total-P optimum is derived in both reports. The supplied square-root total-concentration expression is retained only for comparison. Alpha changes equilibrium peak height/window width, with an unchanged equilibrium peak dose in this network. The high-alpha scenario is not a universal molecular-glue model. Linkers use mapped attachment-point proxies; no real warheads or protein exit-vector orientations were supplied. RMSF and histogram widths are not binding entropy. DC50 uses the rising half-maximum crossing; the single Hill fit is restricted to that limb. Both immunoblot and luminescence data are synthetic.

## Figure previews

{figures}
"""
    path=out/"README.md"
    marker_start="<!-- TASK2-GENERATED-START -->"
    marker_end="<!-- TASK2-GENERATED-END -->"
    block=marker_start+"\n"+readme+"\n"+marker_end
    if path.exists():
        previous=path.read_text(encoding="utf-8")
        if marker_start in previous and marker_end in previous:
            before=previous.split(marker_start)[0]
            after=previous.split(marker_end,1)[1]
            text=before+block+after
        else:
            text=previous.rstrip()+"\n\n"+block+"\n"
    else:
        text=block+"\n"
    path.write_text(text,encoding="utf-8")


def git_publish(out, generated):
    git_directory=out
    def git(*args,check=True):
        return subprocess.run(["git","-C",str(git_directory),*args],check=check,text=True,capture_output=True)
    top=git("rev-parse","--show-toplevel",check=False)
    if top.returncode:
        raise RuntimeError("Git publication unavailable: output is not inside an existing repository")
    repo=Path(top.stdout.strip()).resolve()
    # Generated pathspecs below are relative to the repository, including when
    # this project or the chosen output is nested several directories deep.
    git_directory=repo
    upstream=git("rev-parse","--abbrev-ref","--symbolic-full-name","@{u}",check=False)
    if upstream.returncode:
        raise RuntimeError("Git publication unavailable: no configured upstream; no remote was invented")
    staged=git("diff","--cached","--name-only").stdout.strip()
    if staged:
        raise RuntimeError("Existing staged changes detected; refusing to include unrelated work")
    relative=[p.resolve().relative_to(repo).as_posix() for p in generated]
    git("add","--",*relative)
    diff=git("diff","--cached","--quiet",check=False)
    if diff.returncode==1:
        git("commit","-m",COMMIT_MESSAGE)
    elif diff.returncode!=0:
        raise RuntimeError("Unable to inspect staged Task 2 diff")
    pushed=git("push",check=False)
    if pushed.returncode:
        raise RuntimeError("Git push failed: "+pushed.stderr.strip())
    print("Git commit/push completed.")


def main(argv=None):
    parser=argparse.ArgumentParser(description=__doc__,formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output-dir",type=Path,default=Path(__file__).resolve().parent)
    for name,field in Config.__dataclass_fields__.items():
        parser.add_argument("--"+name.replace("_","-"),type=type(field.default),default=field.default)
    parser.add_argument("--git-publish",action="store_true",help="Commit/push generated Task 2 files in an existing repository with an upstream")
    args=parser.parse_args(argv)
    cfg=Config(**{k:getattr(args,k) for k in Config.__dataclass_fields__})
    cfg.validate()
    out=args.output_dir.resolve()
    out.mkdir(parents=True,exist_ok=True)
    for d in ("figures_task2","data_task2"):
        (out/d).mkdir(exist_ok=True)
    logging.basicConfig(level=logging.INFO,format="%(asctime)s | %(levelname)s | %(message)s",
                        handlers=[logging.StreamHandler(sys.stdout),logging.FileHandler(out/"run_task2.log",mode="w",encoding="utf-8")],force=True)
    start=time.perf_counter()
    LOG.info("Starting Task 2 | parameters=%s",asdict(cfg))
    engine=Equilibrium()
    doses,eq,em=equilibrium_profiles(cfg,engine,out)
    LOG.info("Generating and minimizing linker conformers")
    linkers,lm=linker_ensembles(cfg,out)
    LOG.info("Integrating target turnover with equilibrium recomputed at each step")
    assay=degradation_profiles(cfg,doses,out)
    make_figures(cfg,out,doses,eq,em,linkers,lm,assay)
    validation=validate_numerics(cfg,engine,em,out)
    write_reports(cfg,out,em,lm,assay[2],assay[5],validation)
    versions={"python":platform.python_version(),"numpy":np.__version__,"scipy":scipy.__version__,"matplotlib":matplotlib.__version__,"rdkit":rdkit.__version__}
    requirements="\n".join(f"{k}=={versions[k]}" for k in ("numpy","scipy","matplotlib","rdkit"))+"\n"
    (out/"requirements_task2.txt").write_text(requirements,encoding="utf-8")
    elapsed=time.perf_counter()-start
    LOG.info("Complete | elapsed=%.2f seconds | output=%s | versions=%s",elapsed,out,versions)
    logging.shutdown()
    generated=[out/name for name in ("README.md","TPD_TERNARY_COOPERATIVITY_REPORT_ZH.md","TPD_TERNARY_COOPERATIVITY_REPORT_EN.md","requirements_task2.txt","validation_task2.json","run_task2.log")]
    generated+=sorted((out/"figures_task2").glob("*.png"))+sorted((out/"data_task2").glob("*"))
    script=Path(__file__).resolve()
    # Copy the standalone driver when an alternate output directory was chosen.
    if script.parent!=out:
        (out/script.name).write_bytes(script.read_bytes())
    generated.append(out/script.name)
    hashes={str(p.relative_to(out)).replace("\\","/"):hashlib.sha256(p.read_bytes()).hexdigest() for p in generated}
    manifest=dict(parameters=asdict(cfg),versions=versions,elapsed_seconds=elapsed,validation_status=validation["status"],
                  units=dict(concentration="nM",time="hour",distance="angstrom",energy="kcal/mol"),
                  synthetic_data=True,sha256=hashes)
    dump_json(out/"manifest_task2.json",manifest)
    generated.append(out/"manifest_task2.json")
    if args.git_publish:
        git_publish(out,generated)
    return 0


if __name__=="__main__":
    try:
        sys.exit(main())
    except (ValueError,ArithmeticError,RuntimeError,OSError,subprocess.SubprocessError) as exc:
        LOG.error("Task 2 failed: %s",exc)
        sys.exit(1)
