"""Extend the verified v1 registry with primary-source records inspected 2026-09-29.

This file records metadata already checked during manuscript preparation; running
it performs no network validation and does not certify scientific claims or Q1 status.
"""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]
registry=json.loads((BASE.parent/'references_verified.json').read_text('utf-8-sig'))
records=[
 ('esol2004','ESOL: Estimating Aqueous Solubility Directly from Molecular Structure',['John S. Delaney'],True,2004,'Journal of Chemical Information and Computer Sciences','44','3','1000–1005','10.1021/ci034243x','https://pubs.acs.org/doi/abs/10.1021/ci034243x','publisher_metadata_and_abstract','Original journal name retained; hosted under the current JCIM platform. Local formulas remain approximations'),
 ('cns_mpo','Moving beyond Rules: The Development of a Central Nervous System Multiparameter Optimization (CNS MPO) Approach To Enable Alignment of Druglike Properties',['Travis T. Wager','Xinjun Hou','Patrick R. Verhoest','Anabella Villalobos'],True,2010,'ACS Chemical Neuroscience','1','6','435–449','10.1021/cn100008c','https://pubs.acs.org/doi/10.1021/cn100008c','publisher_metadata_and_author_information','Method lineage only; no transfer of original validation to local assumed pKa/logD values'),
 ('chem_mllm','Developing ChemMLLM as a multimodal large language model for chemistry',['Qian Tan','Di Zhang','Ben Gao'],False,2026,'Cell Reports Physical Science','7','5','103310','10.1016/j.xcrp.2026.103310','https://www.cell.com/cell-reports-physical-science/fulltext/S2666-3864(26)00216-X','publisher_metadata_author_affiliations_and_abstract','Reading-project context only; no local ChemMLLM reproduction claimed; abbreviated verified authors'),
 ('cu_data_driven','Data-driven copper catalysis enables stereoselective fluorocyclopropanation',['Chongyuan Yan','Jiewen Liu','Lin Tan','Yating Chen','Huw M. L. Davies','Zhunzhun Yu','Kuangbiao Liao'],True,2026,'Chem','12','6','102922','10.1016/j.chempr.2025.102922','https://www.sciencedirect.com/science/article/pii/S2451929425005133','publisher_abstract_highlights_and_author_laboratory_record','Copper catalysis, not photocatalysis; issue year 2026 although DOI contains 2025; experimental context, not local calculations'),
 ('single_atom_review','Advanced organic electrosynthesis empowered by single-atom catalysis',['Zezhao Li','Chang-Jie Yang','Wan-Jie Wei','Meiqi Zhu','Tianyou Zhao','Qixuan Zhang','Yong-Zhou Pan','Jiarui Yang','Xin-Yu Wang','Hai-Tao Tang','Wen-Hao Li','Dingsheng Wang'],True,2026,'Chem','12','4','102838','10.1016/j.chempr.2025.102838','https://www.sciencedirect.com/science/article/abs/pii/S2451929425004292','publisher_abstract_and_author_institution_record','Review article; issue year 2026 although DOI contains 2025; no new present-work calculation attributed to this review'),
 ('yang2023','CO₂-mediated organocatalytic chlorine evolution under industrial conditions',['Jiarui Yang','Wen-Hao Li','Hai-Tao Tang','Ying-Ming Pan','Dingsheng Wang','Yadong Li'],True,2023,'Nature','617',None,'519–523','10.1038/s41586-023-05886-z','https://www.nature.com/articles/s41586-023-05886-z','publisher_metadata_abstract_and_data_availability','Original producer of reused source traces; Tang affiliation confirmed as Guangxi Normal University'),
 ('yang2026','High-efficiency organo-electrocatalysts enable both anodic and cathodic reactions',['Jiarui Yang','Guo-Wei Lai','Hai-Tao Tang','Yong-Zhou Pan','Ying-Ming Pan','Wen-hao Li','Deyan Luan','Dingsheng Wang','Yadong Li','Xiong Wen David Lou'],True,2026,'Nature Synthesis','5',None,'1032–1042','10.1038/s44160-026-01039-y','https://www.nature.com/articles/s44160-026-01039-y','publisher_metadata_abstract_and_data_availability','Original producer of reused source traces; Tang affiliation confirmed as Guangxi Normal University'),
 ('aqsoldb','AqSolDB, a curated reference set of aqueous solubility and 2D descriptors for a diverse set of compounds',['M. C. Sorkun','A. Khetan','S. Er'],True,2019,'Scientific Data','6',None,'143','10.1038/s41597-019-0151-1','https://www.nature.com/articles/s41597-019-0151-1','publisher_indexed_metadata','Dataset identity; no reconstruction of missing local predictions'),
 ('etkdg','Better Informed Distance Geometry: Using What We Know To Improve Conformation Generation',['Sereina Riniker'],False,2015,'Journal of Chemical Information and Modeling','55','12','2562–2574','10.1021/acs.jcim.5b00654','https://pubs.acs.org/doi/abs/10.1021/acs.jcim.5b00654','publisher_indexed_metadata_and_abstract','Author list deliberately abbreviated because the inspected publisher extract exposes the first author'),
 ('etkdg2020','Improving Conformer Generation for Small Rings and Macrocycles Based on Distance Geometry and Experimental Torsional-Angle Preferences',['Shuzhe Wang','Jagna Witek'],False,2020,'Journal of Chemical Information and Modeling','60','4','2044–2058','10.1021/acs.jcim.0c00025','https://pubs.acs.org/doi/10.1021/acs.jcim.0c00025','publisher_indexed_metadata_and_methods','Conformer generation methods; abbreviated inspected author list'),
 ('gfn2','GFN2-xTB—An Accurate and Broadly Parametrized Self-Consistent Tight-Binding Quantum Chemical Method with Multipole Electrostatics and Density-Dependent Dispersion Contributions',['Christoph Bannwarth','Sebastian Ehlert','Stefan Grimme'],True,2019,'Journal of Chemical Theory and Computation','15','3','1652–1671','10.1021/acs.jctc.8b01176','https://pubs.acs.org/doi/10.1021/acs.jctc.8b01176','publisher_indexed_metadata_and_abstract','Approximate electronic-structure method attribution'),
 ('pyscf2020','Recent developments in the PySCF program package',['Qiming Sun','Xing Zhang','Samragni Banerjee'],False,2020,'The Journal of Chemical Physics','153',None,'024109','10.1063/5.0006074','https://pyscf.org/about.html','official_software_citation_and_author_institution_record','Official PySCF citation plus https://authors.library.caltech.edu/records/gn0fp-nth15; publisher direct access failed'),
 ('openmm','OpenMM 7: Rapid development of high performance algorithms for molecular dynamics',['Peter Eastman','Jason Swails','John D. Chodera','Robert T. McGibbon','Yutong Zhao','Kyle A. Beauchamp','Lee-Ping Wang','Andrew C. Simmonett','Matthew P. Harrigan','Chaya D. Stern','Rafal P. Wiewiora','Bernard R. Brooks','Vijay S. Pande'],True,2017,'PLOS Computational Biology','13','7','e1005659','10.1371/journal.pcbi.1005659','https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005659','publisher_full_text','Molecular dynamics software attribution'),
 ('wtmeta','Well-Tempered Metadynamics: A Smoothly Converging and Tunable Free-Energy Method',['Alessandro Barducci','Giovanni Bussi','Michele Parrinello'],True,2008,'Physical Review Letters','100','2','020603','10.1103/PhysRevLett.100.020603','https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.100.020603','publisher_metadata_and_abstract','Method reference does not certify convergence of archived short trajectories'),
 ('vina','AutoDock Vina: Improving the speed and accuracy of docking with a new scoring function, efficient optimization, and multithreading',['Oleg Trott','Arthur J. Olson'],True,2010,'Journal of Computational Chemistry','31','2','455–461','10.1002/jcc.21334','https://onlinelibrary.wiley.com/doi/10.1002/jcc.21334','publisher_metadata_and_abstract','2010 issue year; first online 2009. Docking score is not binding free energy'),
 ('qrrho','Supramolecular Binding Thermodynamics by Dispersion-Corrected Density Functional Theory',['Stefan Grimme'],True,2012,'Chemistry – A European Journal','18','32','9955–9964','10.1002/chem.201200497','https://chemistry-europe.onlinelibrary.wiley.com/doi/abs/10.1002/chem.201200497','publisher_metadata_and_abstract','Soft-mode treatment precedent; simple frequency flooring is not claimed to reproduce this method'),
]
for key,title,authors,complete,year,journal,volume,issue,pages,doi,url,access,note in records:
    registry['references'].append({'id':f"R{len(registry['references'])+1:02d}",'citation_key':key,'title':title,'authors':authors,'author_list_complete':complete,'year':year,'journal':journal,'volume':volume,'issue':issue,'pages_or_article':pages,'doi':doi,'url':url,'publication_status':'published','reference_role':'method_or_dataset','verified_source':[{'url':url,'source_type':'primary_record','access_level':access,'verified_fields':['title','listed_authors','year','journal','volume','pages_or_article','doi']}],'verification_note':note,'verified_on':'2026-09-29','journal_quartile_verified':False})
extra_sources={
 'cu_data_driven':'https://www.daviesresearchgroup.com/publications',
 'single_atom_review':'https://scholars.cityu.edu.hk/en/publications/advanced-organic-electrosynthesis-empowered-by-single-atom-cataly/'
}
for ref in registry['references']:
    if ref['citation_key'] in extra_sources:
        ref['verified_source'].append({'url':extra_sources[ref['citation_key']],'source_type':'author_laboratory_or_institution','access_level':'publication_metadata','verified_fields':['full_author_list','title','year','doi']})
registry['reference_count']=len(registry['references'])
registry['tang_gxnu_author_verified_count']=6
registry['additional_tang_coauthored_review_count']=1
registry['verified_on']='2026-09-29 (new entries); 2026-09-28 (inherited entries)'
registry['expanded_source_inventory']='manuscript/history/repository_inventory.json'
(BASE/'references_verified.json').write_bytes((json.dumps(registry,ensure_ascii=False,indent=2)+'\n').encode())
print(registry['reference_count'])
