"""Derive isolated publication tools from the preserved v1 implementation."""
from pathlib import Path
BASE=Path(__file__).resolve().parents[1]
old=BASE.parent/'scripts';new=BASE/'scripts'
s=(old/'finalize_references.py').read_text('utf-8-sig')
s=s.replace('REPO = BASE.parent','REPO = BASE.parent.parent')
s=s.replace('    "supporting_information_english.md",\n    "supporting_information_chinese.md",\n','')
s=s.replace('((SOURCES[0], SOURCES[1]), (SOURCES[2], SOURCES[3]))','((SOURCES[0], SOURCES[1]),)')
s=s.replace('flatten(parsed[SOURCES[0]]) + flatten(parsed[SOURCES[2]])','flatten(parsed[SOURCES[0]])')
s=s.replace('First appearance in English main text, then English SI','First appearance in expanded English main text')
s=s.replace('main manuscripts and supporting information','expanded main manuscripts').replace('manuscript or supporting information','expanded manuscripts')
(new/'finalize_references.py').write_bytes(s.encode())
s=(old/'build_documents.py').read_text('utf-8-sig')
s=s.replace('ROOT = Path(__file__).resolve().parents[2]','ROOT = Path(__file__).resolve().parents[3]')
s=s.replace("BASE = ROOT / 'manuscript'","BASE = ROOT / 'manuscript' / 'expanded'")
s=s.replace("NAMES = ['manuscript_english', 'manuscript_chinese', 'supporting_information_english', 'supporting_information_chinese']","NAMES = ['manuscript_english', 'manuscript_chinese']")
s=s.replace('Build four journal-style DOCX editions','Build two expanded journal-style DOCX editions')
s=s.replace('Reference bias and observable dependent convergence','Reference and observable dependence in molecular learning and multiscale computational chemistry')
s=s.replace("if any('source' in c.lower() or '源码' in c for c in rows[0]):", "if n==3 and any('source' in c.lower() or '源码' in c for c in rows[0]):")
(new/'build_documents.py').write_bytes(s.encode())
s=(old/'render_equations.py').read_text('utf-8-sig').replace('the five supplied','the supplied')
(new/'render_equations.py').write_bytes(s.encode())
s=(old/'inspect_documents.py').read_text('utf-8-sig')
s=s.replace("NAMES=['manuscript_english','manuscript_chinese','supporting_information_english','supporting_information_chinese']","NAMES=['manuscript_english','manuscript_chinese']")
s=s.replace("expected_figures=6 if name.startswith('manuscript') else 0","expected_figures=json.loads((BASE/'results'/'assembly.json').read_text('utf-8'))['documents'][name]['figures']")
s=s.replace("'all_pages_letter':", "'at_least_30_pages':len(pages)>=30,\n            'all_pages_letter':")
s=s.replace("'page_count':len(pages)","'page_count':len(pages),'reference_start_page':next((i+1 for i,t in enumerate(alltext) if re.search(r'(?:^|\\n)(?:References|参考文献)\\s*(?:\\n|$)',t)),None)")
(new/'inspect_documents.py').write_bytes(s.encode())
print('Isolated publishers prepared; preserved v1 tools unchanged.')
